# LoL チャンピオン名 日本語 -> 英語 マッピング
CHAMPION_MAP = {
    "エイトロックス": "Aatrox", "アーリ": "Ahri", "アカリ": "Akali", "アリスター": "Alistar",
    "アムム": "Amumu", "アニビア": "Anivia", "アニー": "Annie", "アフェリオス": "Aphelios",
    "アッシュ": "Ashe", "アウレリオン・ソル": "Aurelion Sol", "アジール": "Azir", "バード": "Bard",
    "ベル＝ヴェス": "Bel'Veth", "ブリッツクランク": "Blitzcrank", "ブランド": "Brand", "ブラウム": "Braum",
    "ブライアー": "Briar", "ケイトリン": "Caitlyn", "カミール": "Camille", "カシオペア": "Cassiopeia",
    "チョ＝ガス": "Cho'Gath", "コーキー": "Corki", "ダリウス": "Darius", "ダイアナ": "Diana",
    "ドクター・ムンド": "Dr. Mundo", "ドレイヴン": "Draven", "エコー": "Ekko", "エリス": "Elise",
    "イブリン": "Evelynn", "エズリアル": "Ezreal", "フィドルスティックス": "Fiddlesticks", "フィオラ": "Fiora",
    "フィズ": "Fizz", "ガリオ": "Galio", "ガングプランク": "Gangplank", "ガレン": "Garen",
    "ナー": "Gnar", "グラガス": "Gragas", "グレイブス": "Graves", "グウェン": "Gwen",
    "ヘカリム": "Hecarim", "ハイマーディンガー": "Heimerdinger", "フナオ": "Hwei", "イラオイ": "Illaoi",
    "イレリア": "Irelia", "アイバーン": "Ivern", "ジャンナ": "Janna", "ジャーヴァンIV": "Jarvan IV",
    "ジャーヴァン": "Jarvan IV", "ジャックス": "Jax", "ジェイス": "Jayce", "ジン": "Jhin",
    "ジンクス": "Jinx", "カ＝サ": "Kai'Sa", "カリスタ": "Kalista", "カルマ": "Karma",
    "カーサス": "Karthus", "カサディン": "Kassadin", "カタリナ": "Katarina", "ケイル": "Kayle",
    "ケイン": "Kayn", "ケネン": "Kennen", "カ＝ジックス": "Kha'Zix", "キンドレッド": "Kindred",
    "クレッド": "Kled", "コグ＝マウ": "Kog'Maw", "ルブラン": "LeBlanc", "リー・シン": "Lee Sin",
    "レオナ": "Leona", "リリア": "Lillia", "ルシアン": "Lucian", "ルル": "Lulu",
    "ラックス": "Lux", "マルファイト": "Malphite", "マルザハール": "Malzahar", "マオカイ": "Maokai",
    "マスター・イー": "Master Yi", "ミリオ": "Milio", "ミス・フォーチュン": "Miss Fortune", "ナフィリ": "Naafiri",
    "ナミ": "Nami", "ナサス": "Nasus", "ノーチラス": "Nautilus", "ニーコ": "Neeko",
    "ニダリー": "Nidalee", "ニラー": "Nilah", "ノクターン": "Nocturne", "ヌヌ": "Nunu",
    "オラフ": "Olaf", "オリアナ": "Orianna", "オーン": "Ornn", "パンテオン": "Pantheon",
    "ポッピー": "Poppy", "パイク": "Pyke", "キヤナ": "Qiyana", "クイン": "Quinn",
    "ラカン": "Rakan", "ラムス": "Rammus", "レク＝サイ": "Rek'Sai", "レル": "Rell",
    "レナータ・グラスク": "Renata Glasc", "レネクトン": "Renekton", "レンガー": "Rengar", "リヴェン": "Riven",
    "ランブル": "Rumble", "ライズ": "Ryze", "サミーラ": "Samira", "セジュアニ": "Sejuani",
    "セナ": "Senna", "セラフィーン": "Seraphine", "セト": "Sett", "シャコ": "Shaco",
    "シェン": "Shen", "シヴァーナ": "Shyvana", "シンジド": "Singed", "サイオン": "Sion",
    "シヴィア": "Sivir", "スカーナー": "Skarner", "ソナ": "Sona", "ソラカ": "Soraka",
    "スウェイン": "Swain", "サイラス": "Sylas", "シンドラ": "Syndra", "タム・ケンチ": "Tahm Kench",
    "タリヤ": "Taliyah", "タロン": "Talon", "タリック": "Taric", "ティーモ": "Teemo",
    "スレッシュ": "Thresh", "トリスターナ": "Tristana", "トリンダメア": "Tryndamere", "ツイステッド・フェイト": "Twisted Fate",
    "トゥイッチ": "Twitch", "ウディア": "Udyr", "ウルゴット": "Urgot", "ヴァルス": "Varus",
    "ヴェイン": "Vayne", "ベイガー": "Veigar", "ヴェル＝コズ": "Vel'Koz", "ベックス": "Vex",
    "ヴァイ": "Vi", "ヴィエゴ": "Viego", "ヴィクトル": "Viktor", "ブラッドミア": "Vladimir",
    "ボリベア": "Volibear", "ワーウィック": "Warwick", "ウーコン": "Wukong", "ザヤ": "Xayah",
    "ゼラス": "Xerath", "シン・ジャオ": "Xin Zhao", "ヤスオ": "Yasuo", "ヨネ": "Yone",
    "ヨーリック": "Yorick", "ユミ": "Yuumi", "ザック": "Zac", "ゼド": "Zed",
    "ゼリ": "Zeri", "ジグス": "Ziggs", "ジリアン": "Zilean", "ゾーイ": "Zoe",
    "ザイラ": "Zyra"
}

def translate_champion(name):
    """日本語名があれば英語名に変換する"""
    return CHAMPION_MAP.get(name, name)
