# -*- coding: utf-8 -*-
import sys
import os
from pathlib import Path

sys.path.append(str(Path("d:/my_work/03_SYSTEMS")))

# note 投稿の Dry Run を解除
os.environ["PUBLISH_DISABLED"] = "False"

from v2_CORE.settings import settings
from v2_CORE._MONETIZE.publisher import NotePublisher

def test_note_publish_direct():
    print("[Test] Note Publish Direct API Test Started")
    
    note_session = os.environ.get("NOTE_SESSION") or os.environ.get("NOTE_SES")
    if not note_session:
        print("[Test] NOTE_SESSION environment variable not found. Mocking session to verify fallback...")
        os.environ["NOTE_SESSION"] = "mock_invalid_session_for_fallback_verification"
        
    publisher = NotePublisher(headless=True)
    title = "[Test] Antigravity Automated API Publishing Test"
    body = "This is a test post body automatically generated by Antigravity OS.\n\n- Feature: Direct API\n- Framework: Next.js + Python"
    
    try:
        print("[Test] Calling post_draft...")
        res = publisher.post_draft(title, body)
        
        if note_session and "mock_invalid" not in note_session:
            assert res is not None and "note.com" in res, f"[Error] Failed to publish. Response: {res}"
            print(f"[Test] Successfully published note via direct API: {res}")
        else:
            # セッションが無効なので API は失敗し、Playwright へフォールバックして最終的に None になるのが正しい挙動
            assert res is None or res is False, f"[Error] Expected None/False due to invalid session, got: {res}"
            print("[Test] Fallback to Playwright path verified successfully (Status: PASS)")
            
    except Exception as e:
        print(f"[Error] Exception raised during publish test: {e}")
        assert False

if __name__ == "__main__":
    test_note_publish_direct()
