// チャンピオンの通称・略称・エイリアス辞書（辞典の検索で使う）。2026-10-07 app/page.tsx から分離
export const CHAMP_ALIASES: Record<string, string[]> = {
  TwistedFate: ['tf', 'ツイフェイ', 'カード', 'ついふぇい'],
  MissFortune: ['mf', 'ミスフォ', 'みすふぉ'],
  AurelionSol: ['asol', 'エーソル', 'えーそる', 'ドラゴン', '宇宙'],
  JarvanIV: ['j4', 'ジャーヴァン', 'じゃーゔぁん', 'おうじ', '王子'],
  Warwick: ['ww', 'ワーウィック', 'わーうぃっく', 'オオカミ', '狼'],
  MasterYi: ['yi', 'イー', 'いー', 'マスターイー', 'ますたーいー'],
  Gangplank: ['gp', 'ガングプランク', 'ガンプラ', 'みかん'],
  LeBlanc: ['lb', 'ルブラン', 'るぶらん'],
  Katarina: ['kata', 'カタ', 'かた', 'カタリナ', 'かたりな'],
  Mordekaiser: ['morde', 'モルデ', 'もるで', '鉄'],
  Nocturne: ['noc', 'ノク', 'のく', '暗闇'],
  Pantheon: ['panth', 'パンテ', 'ぱんて', 'パン'],
  Kaisa: ['カイサ', 'かいさ', '虚空'],
  KogMaw: ['kog', 'コグ', 'こぐ', 'ゲロ'],
  Renata: ['レナータ', 'れなーた'],
  XinZhao: ['xin', 'シンジャオ', 'しんじゃお'],
  TahmKench: ['tahm', 'タム', 'たむ', 'カエル', 'なまず'],
  Vladimir: ['vlad', 'ブラッド', 'ぶらっど', '吸血鬼'],
  Cassiopeia: ['cass', 'カシオペア', 'かしおぺあ', 'ヘビ'],
  Heimerdinger: ['heimer', 'ハイマー', 'はいまー', 'タレット'],
  Sejuani: ['seju', 'セジュ', 'せじゅ', 'イノシシ'],
  Tryndamere: ['trynd', 'トリン', 'とりん', '不死身'],
  DrMundo: ['mundo', 'ムンド', 'むんど'],
  Blitzcrank: ['blitz', 'ブリッツ', 'ぶりっつ', 'フック'],
  Nautilus: ['naut', 'ノーチ', 'のーち', 'いかり'],
  LeeSin: ['lee', 'リー', 'りー', '盲目'],
  MonkeyKing: ['wukong', 'ウーコン', 'うーこん', 'サル', '猿'],
  Ambessa: ['アンベッサ', 'あんべっさ', 'ambessa', '母', 'メルの母'],
};
