// This file is auto-generated by copy_design.js. Do not edit directly.

export interface DesignDoc {
  title: string;
  content: string;
  filename: string;
}

export const systemDesignDocs: Record<string, DesignDoc> = {
  "overview": {
    title: "🌟 全体概要・自動化デーモン",
    filename: "00_overview.md",
    content: `# Sovereign OS & KTM Bot 全体概要・自動化デーモン

Sovereign OSは、ポータルサイト、Discord Bot（KTM Bot）、Google Sheets、およびバックエンドのPythonデーモンを統合したイベント駆動型システムです。

---

## 1. システム全体構成図

\`\`\`mermaid
graph TD
    User[ユーザー / プレイヤー] <--> |Discord Bot / ボタン| Discord[Discord Server]
    User <--> |Webブラウザ| Portal[Web Portal (Next.js)]
    Discord <--> |Webhook| Workers[KTM Bot (Cloudflare Workers)]
    Workers <--> |API Call| GAS[Google Apps Script]
    GAS <--> |Read/Write| Sheets[Google Sheets (MMR)]
    Portal <--> |Read/Write| Supabase[(Supabase DB)]
    
    subgraph Sovereign_OS_Core [Sovereign OS Core Engine]
        SREDaemon[SRE Daemon]
        YTAbsorber[YouTube Absorber]
        Monetize[Monetization Batch]
        NotionSync[Notion Sync]
    end
    
    SREDaemon --> |Watch Log / Healer| Supabase
    YTAbsorber <--> |Read Queue / 要約| Supabase
    Monetize <--> |note/X自動投稿| Supabase
    NotionSync <--> |Notionメモ同期| Supabase
    Sovereign_OS_Core <--> |AI生成| Gemini[Gemini API]
\`\`\`

---

## 2. 自律AI自動化デーモン (Python - v2_CORE)

* **AI Healer / SRE デーモン (\`sre_daemon.py\` / \`healer.py\`)**:
  ポータルやBotのビルドログ、例外エラーを監視し、AIが自動でTypeScript等のコードを修復してGit Pushデプロイを行います。
* **YouTube攻略動画要約 (\`youtube_absorber.py\`)**:
  指定されたYouTubeチャンネルを巡回し、\`yt-dlp\`で字幕抽出 ➔ Geminiで攻略マニュアル化 ➔ チャンピオン辞典へマージします。
* **note自動執筆・投稿 (\`monetization_batch.py\`)**:
  LoLメタトレンドを自動分析し、アフィリエイト付きの有料/無料記事を執筆。Playwrightでnoteに下書き保存し、X(Twitter)に連続スレッドを自動投稿します。
* **Notion同期 (\`sovereign_sync.py\`)**:
  Notionの反省データベースから自分のLoLメモを定期検知し、Supabaseの \`personal_knowledge\` へ同期します。
`
  },
  "balancer": {
    title: "🎮 KTM Bot ＆ レーン優先度",
    filename: "01_balancer.md",
    content: `# 🎮 Discord KTM大会運営機能 ＆ 希望レーン調停

Discord Bot（KTM Bot）は、カスタム内戦の募集から、プレイヤーのレーン希望・こだわり度を調停したチーム分けまでを実行します。

---

## 1. コマンド一覧 (\`handlers/commands.js\`)

* **\`/recruit\` (メンバー募集)**:
  カスタム(10人)/ノーマル(5人)/ARAMの募集Embedを投稿。定員時に自動締め切り、\` balance \` チーム分けボタンを生成。
* **\`/lane\` (希望設定)**:
  メイン/サブ希望レーン、NG1/NG2、こだわり度(1〜3)、格上対面許容を登録。モーダル入力フォームに対応。
* **\`/balance\` (チーム分け実行)**:
  VCにいる10人または募集枠の10人から自動チーム分け。レーン配置・戦力平準化アルゴリズムを適用。
* **\`/stats\` (戦績確認)**:
  個人の総合勝率、直近5試合の勝敗、レーン別MMR、Pity値をEmbed投稿。
* **\`/sync\` (手動同期)**:
  スプレッドシートやRiot APIとSupabaseの手動同期を実行。

---

## 2. 特殊ハンドラー

* **コンポーネント操作 (\`handlers/components.js\`)**:
  - \`どこでも参加\`、\`観戦希望\`、\`離脱\` ボタンの登録処理。
  - \`代理追加\` (管理者がゲストを直接追加)、\`一括連絡\` (全員メンション)。
  - \`BLUE勝利\` / \`RED勝利\` 勝敗報告ボタンによるMMR・Pity再計算。
  - \`次戦へ移行\`: 出場・待機枠を引き継いで自動で次戦の募集を開始。
* **スケジュール同期 (\`handlers/scheduled.js\`)**:
  - Discordスケジュールイベント（カスタム予定）の開始30分前・10分前に自動で \`/recruit\` 募集パネルをチャンネルに投稿。
`
  },
  "match_record": {
    title: "📈 MMR・Pity アルゴリズム仕様",
    filename: "02_match_record.md",
    content: `# 📈 チーム分けペナルティ ＆ レート（MMR）計算式

公平なゲーム体験を実現するための数理最適化と Elo レーティング補正ロジック。

---

## 1. レーン配置ペナルティ算出アルゴリズム

配置パターンに対して以下のペナルティを計算し、合計ペナルティが最小の組み合わせを自動決定する。

$$\\text{Total Penalty} = \\sum_{p \\in \\text{Players}} (\\text{Role Penalty}(p) + \\text{Pity Penalty}(p) + \\text{NG Penalty}(p) + \\text{Job Penalty}(p))$$

* **NG Penalty**: NGレーンに配置された場合、**+2,000,000 点**。
* **Role Penalty**: サブ配置で $+20,000 \\times \\text{weight\\_factor}$、希望外で $+500,000 \\times \\text{weight\\_factor}$。
  - こだわり度1 (絶対) ➔ $\\text{weight\\_factor} = 50.0$ (サブ配置をほぼ絶対阻止)
  - こだわり度2 (通常) ➔ $\\text{weight\\_factor} = 1.0$
  - こだわり度3 (柔軟) ➔ $\\text{weight\\_factor} = 0.25$
* **Pity Penalty**: 前回の不満度。$(\\text{Pity} \\times 10,000 \\text{〜} 50,000)$ をマイナスし、我慢した人を優先配置。
* **Job Penalty**: JG, SUP, ADC専が他レーンに行く際、ペナルティを **2倍〜3倍** にブースト。
* **初心者保護**: 参加3戦未満の初心者をJG/MIDに振る際、**+1,000,000 点**。

---

## 2. Pity（不運度）蓄積ルール
* **メインロール配置**: 0 にリセット。
* **サブロール配置**: +2。
* **希望外ロール配置**: +5。
* **出場できず待機枠**: +10。
* 11人以上いる場合は **Pity値の高い順** に優先出場。

---

## 3. MMR計算公式（改良型 Elo レーティング）

$$\\text{MMR}_{\\text{new}} = \\text{MMR}_{\\text{old}} + K \\cdot (\\text{Actual} - \\text{Expected}) + \\text{KDA Bonus} + \\text{Placement Gravity}$$

* $K$: 変動幅係数（48）。
* $\\text{Expected}$ (予測勝率):
  
  $$\\text{Expected} = \\frac{1}{1 + 10^{\\frac{\\text{MMR}_{\\text{opponent}} - \\text{MMR}_{\\text{self}}}{400}}}$$
  
* $\\text{KDA Bonus}$: 個人KDA成績から最大 $\pm 20$。
* $\\text{Placement Gravity}$: 10戦未満のプレイヤーに対し、公式最高ランクに基づく基礎レートに引き寄せる補正。
* **ブースト倍率**: 5戦未満は **3倍**、10戦未満は **2倍**、直接対面回数が少ない相手との試合は最大 **1.5倍** 変動。
`
  },
  "leaderboard": {
    title: "🏆 分析ポータル・勝率マトリクス",
    filename: "03_leaderboard.md",
    content: `# 🏆 分析ポータル・プレイヤー間勝率マトリクス

ポータルサイト（04_PORTAL）が提供する、カスタム戦績の高度な分析ページ群。

---

## 1. ポータル全稼働画面

* **チームバランサーWeb版 (\`/balancer\`)**:
  ドラッグ＆ドロップでチーム分けをシミュレーションし、結果を直接Supabaseに記録。
* **対戦履歴一覧 (\`/history\`)**:
  過去のカスタム試合ログ一覧。勝敗、日付、各プレイヤーのチャンピオンとKDAスタッツのアコーディオン展開表示。
* **リーダーボード (\`/leaderboard\`)**:
  プレイヤー別MMRランキング、総合勝率、KDA順位の表示。
* **勝率総当たりマトリクス (\`WinrateMatrixPanel.tsx\`)**:
  リーダーボード画面内の目玉機能。プレイヤー同士が「同じチームだった時の勝率（シナジー）」と「直接対面だった時の勝率（相性）」を総当たりマトリクスで可視化するヒートマップ。
* **デュオシナジー分析 (\`/synergy\`)**:
  プレイヤー2名を選択し、味方時／敵対時の勝率、合計対戦数、シナジー評価を抽出。
* **個人スタッツ詳細 (\`/stats/[discord_id]\` / \`/player/[id]\`)**:
  プレイヤー個人のレーン別勝率、使用チャンプ勝率トップ5、KDAのヒストグラム分布、Pity値の推移グラフ。
`
  },
  "vs_analytics": {
    title: "⚔️ リアルタイム偵察 ＆ 辞典",
    filename: "04_vs_analytics.md",
    content: `# ⚔️ リアルタイム偵察 ＆ チャンピオン事前学習マニュアル

ソロキューの進行中マッチ対策、およびチャンピオンマッチアップ攻略辞典。

---

## 1. ソロキュー対戦相手偵察 (Live Lookup - \`/admin/soloq\`)

* **概要**:
  現在進行中のライブゲームを検知し、敵ジャングラーのルートや対策をリアルタイム分析。
* **詳細仕様**:
  - PUUID解決、Spectator API経由のゲームフェッチ、敵ジャングラー特定、過去戦績Timeline取得。
  - GLOBALナレッジ（\`matchup_sentinel\`）および過去の自分の敗因反省（\`personal_knowledge\`）をマージし、AIリアルタイム指示3箇条を生成。
  - 過去のやらかし反省がある場合、最上部で赤いバナーが点滅。
  - **エラーハンドリング**: \`RIOT_API_KEY\` 未設定時はモックを表示せず、エラーメッセージを直接描画。

---

## 2. Junglepediaレプリカ ＆ AIアドバイザー (\`/player/[id]/junglepedia\`)

* **仕様**:
  Junglepedia.lol のデザインを再現。6大スライダー（ルート固定率、開始サイド、赤青選択、オブジェクト vs 戦闘、アグレッシブ度、クリア速度）、オブジェクト獲得率、標準フルクリア時間を表示。
* **AI戦術アドバイス**:
  スライダー数値を分析し、本人向けの勝率UPアドバイスと、敵視点での対策をトグル表示。APIキー未設定時はモックを表示せず、赤色警告バナーを描画。

---

## 3. チャンピオンマッチアップ比較 (\`/matchups\`)
* **仕様**:
  チャンピオン2体を選択し、対面統計データ、レーンごとのキル関与度やパワースパイクの違いをグラフィカルに比較表示する90KBの超巨大スタッツ画面。

---

## 4. チャンピオン辞典 ＆ 過去の敗因反省 (\`/champions\`)
* **仕様**:
  各チャンピオンの強み・弱み、ビルド、パワースパイク解説と、過去の自分の敗因反省履歴（やらかしメモ）を表示。
`
  },
  "knowledge_base": {
    title: "🧠 ナレッジ ＆ プロンプト管理",
    filename: "05_knowledge_base.md",
    content: `# 🧠 ナレッジ管理 ＆ AIプロンプトテンプレート管理

管理者専用のデータ同期、分析、プロンプトの動的編集コントロール。

---

## 1. 管理者ダッシュボード (\`/ktm-admin\` / \`/admin/dashboard\`)

* **MMR再構築 (\`api/mmr/rebuild\`)**:
  過去のすべての試合ログをスプレッドシートから再読み込みし、初期からMMRを時系列で一括再計算。
* **整合性検証 (\`api/mmr/check-integrity\` / \`check-integrity\`)**:
  データベース上の現在MMRが、試合ログの累積変動計算とズレていないかをテスト・照合する整合性スキャン。

---

## 2. アフィリエイト収益分析 (\`/admin/analytics\`)
* **仕様**:
  note記事のPV推移、アフィリエイトクリック数、アクセス数ランキング、PV推移データのグラフ化。

---

## 3. ジャングルクリアタイム管理 (\`/admin/clears\`)
* **仕様**:
  各プレイヤーの得意チャンピオン別のクリア時間の秒数・ルートデータをデータベース管理。

---

## 4. AIプロンプトテンプレート管理 (\`/admin/prompts\`)
* **仕様**:
  AI Healer、note自動執筆、リアルタイム偵察対策生成で使用している各種システムプロンプト・ユーザープロンプトテンプレートを管理画面から動的に上書き編集できる機能。
`
  }
};
