// This file is auto-generated by copy_design.js. Do not edit directly.

export interface DesignDoc {
  title: string;
  content: string;
  filename: string;
}

export const systemDesignDocs: Record<string, DesignDoc> = {
  "overview": {
    title: "🌟 全体概要・アーキテクチャ",
    filename: "00_overview.md",
    content: `# Sovereign OS & KTM Bot 全体概要・アーキテクチャ設計

Sovereign OS プロジェクトにおける、Webポータル、大会運営Bot (KTM Bot)、コア自動化エンジン、およびデータベース (Supabase) の全体像、機能、データ連携、およびロジックの設計仕様を詳細に定義します。

---

## 1. システム全体アーキテクチャ (System Architecture)

Sovereign OS は、Supabase データベースおよび Google Sheets を中心とし、フロントエンド（Next.js / Discord）とバックエンド自動化エンジン（Python Core / Cloudflare Workers / GAS）が連携する分散イベント駆動型アーキテクチャです。

### 1-1. システム関連図

\`\`\`mermaid
graph TD
    %% ユーザーおよびインターフェース
    User[ユーザー / プレイヤー] <--> |Discord Slash Cmd / UI| Discord[Discord Server]
    User <--> |Webブラウザ| Portal[Web Portal (Next.js)]

    %% Discord Bot 連携
    Discord <--> |Interactivity Webhook| Workers[KTM Bot (Cloudflare Workers)]
    Workers <--> |HTTPS API Call| GAS[Google Apps Script (GAS)]
    GAS <--> |Read/Write| Sheets[Google Sheets (DB/MMR)]
    GAS <--> |HTTP Trigger| PortalAPI[Portal API (Next.js)]

    %% Webポータル 連携
    Portal <--> |Read/Write| Supabase[(Supabase DB)]
    PortalAPI <--> |Read/Write| Supabase

    %% Sovereign OS コア (Python)
    subgraph Sovereign_OS_Core [Sovereign OS Core Engine]
        SREDaemon[SRE Daemon]
        DictSynthesizer[Dict Synthesizer]
        YTAbsorber[YouTube Absorber]
        RedditScout[Reddit Scout]
        Pulse[Sovereign Pulse]
    end

    SREDaemon --> |Watch Log / Cleanup| Supabase
    SREDaemon --> |Metrics Save| Supabase
    DictSynthesizer <--> |Fetch / Merge / Mark deleted| Supabase
    YTAbsorber <--> |Read Queue / Write Video Data| Supabase
    RedditScout <--> |Scrape Trends / Write Articles| Supabase
    Pulse --> |Observer SoloQ / Scraping| Supabase
    Sovereign_OS_Core <--> |AI Request| Gemini[Gemini API (ai_helper)]
\`\`\`

---

## 2. データベース設計 (Database Schema & Security)

### 2-1. Supabase テーブル定義

#### A. \`bible_articles\` (攻略ライブラリ記事)
マクロ判断や、各チャンピオンごとの攻略バイブル記事、および一時的なトレンド記事をMarkdown形式で保存します。

| カラム名 | データ型 | 制約 | 説明 |
| :--- | :--- | :--- | :--- |
| \`id\` | int8 | PRIMARY KEY (Identity) | 記事の一意ID |
| \`created_at\` | timestamptz | DEFAULT \`now()\` | 作成日時 |
| \`title\` | text | UNIQUE | 記事タイトル (例: \`[総合バイブル] マクロ\`) |
| \`content\` | text | - | 記事本文 (Markdown形式) |
| \`champion\` | text | - | 対象チャンピオン名 (指定なしは \`Unknown\`, \`GLOBAL\` 等) |
| \`keywords\` | text[] | - | 検索タグ・ジャンル名 (例: \`["マクロ", "総合バイブル"]\` / 削除用タグは \`["__DELETED__"]\`) |
| \`file_path\` | text | - | ローカルのMarkdownファイルの保存先絶対パス |

#### B. \`matchup_sentinel\` (チャンピオン辞典 & 戦術データ)
各チャンピオンごとの対策やGLOBALなマクロ、さらにダッシュボード用システムメトリクス（ID: \`SYSTEM_METRICS\`）を保持します。

| カラム名 | データ型 | 制約 | 説明 |
| :--- | :--- | :--- | :--- |
| \`id\` | int8 | PRIMARY KEY (Identity) | レコードの一意ID |
| \`created_at\` | timestamptz | DEFAULT \`now()\` | 作成日時 |
| \`matchup_id\` | text | UNIQUE | 識別キー (例: \`GLOBAL\`, \`SYSTEM_METRICS\`, \`{ChampName}_GLOBAL\`) |
| \`title\` | text | - | チャンピオン名やタイトル |
| \`champion\` | text | - | チャンピオン名 |
| \`enemy\` | text | - | 対面チャンピオン名 (基本対策は \`GLOBAL\`) |
| \`strategy\` | text | - | 対面戦術・反省会から得られた鬼コーチの教訓 |
| \`raw_data\` | jsonb | - | 拡張用JSONデータ。\`note_draft\` (noteドラフト原稿) や \`logs\` (最新ログ)、\`queue\` (YouTubeキュー件数) を内包 |

#### C. \`api_usage_logs\` (API使用量ログ)
1日あたりのAPI（Gemini等）の消費トークン・リクエスト数を蓄積し、クォータオーバーを防止します。

| カラム名 | date | PRIMARY KEY | 利用日 (日付) |
| :--- | :--- | :--- | :--- |
| \`calls\` | jsonb | - | 機能ごとのAPI呼び出し回数・エラーカウント履歴 |

---

### 2-2. Row Level Security (RLS) ポリシー

全世界に安全に公開するため、Supabase上の各テーブルに以下のRLSを適用しています。

\`\`\`sql
-- 読み取り許可 (未認証の一般ユーザーを含め、全員に許可)
CREATE POLICY "Allow read for all" ON bible_articles FOR SELECT USING (true);
CREATE POLICY "Allow read for all" ON matchup_sentinel FOR SELECT USING (true);

-- 書き込み・更新許可 (認証済み管理者アカウントのみに制限)
CREATE POLICY "Allow insert for admin" ON bible_articles FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow update for admin" ON bible_articles FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow delete for admin" ON bible_articles FOR DELETE TO authenticated USING (true);

CREATE POLICY "Allow insert for admin" ON matchup_sentinel FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow update for admin" ON matchup_sentinel FOR UPDATE TO authenticated USING (true);
\`\`\`
*※ローカルまたはVPSで動作する Python Core モジュールは、認証をバイパスする \`service_role\` キーを使用して書き込みを行います。*
`
  },
  "balancer": {
    title: "⚖️ MMRバランサー・チーム分け",
    filename: "01_balancer.md",
    content: `# ⚖️ MMRバランサー・チーム分け機能

登録されているプレイヤーの希望ロール、実力（MMR）、および過去の待機状況（不満度）に基づいて、実力が最も均等であり、かつ不満度が最小になる2つのチーム（Blue / Red）を自動編成する機能です。

---

## 1. 概要とデータ連携

*   **データソース（取得元）**: 
    *   Supabase \`ktm_players\` テーブルからプレイヤー名、各ロールのMMR（初期値: 1200）、および \`pity\`（不満度カウンター）を取得します。
*   **データ追加・更新トリガー**:
    *   新規プレイヤーデータは Discord Bot または管理者画面から手動で登録されます（自動追加はありません）。
    *   各ロールのMMRおよびPityは、後述の **「対戦結果登録」** の手動送信時に自動的に更新（UPDATE）されます。
*   **公開区分**: 一般ユーザー向け（誰でも実行可能）

---

## 2. ロール配置ペナルティ最小化アルゴリズム

チーム分けの際、全プレイヤーのレーン配置候補パターンに対してペナルティを計算し、合計ペナルティが最小になる組み合わせを選出します。

### 2-1. 配置ペナルティ値の定義
*   **希望外レーン（メイン・サブ以外）への配置**: \`500,000 pt\`
*   **サブレーン（第2希望）への配置**: \`20,000 pt\`
*   **NGレーン（絶対にやりたくないレーン）への配置**: \`2,000,000 pt\`（絶対に回避するペナルティ）

### 2-2. こだわり度 (Weight) の調整補正
*   **「絶対（weight=1）」に設定しているレーン**: 希望レーンから外れた場合、ペナルティを **50倍** に増幅し配置を絶対回避します。
*   **「柔軟（weight=3）」に設定しているレーン**: 希望外またはサブ配置時のペナルティを **1/4** に軽減し、他のプレイヤーの希望を優先します。

### 2-3. Pity (不満度) による割引補正
*   プレイヤーが希望レーンに配置されなかった場合、Pityカウンターが加算されます（サブ配置で \`+2\`、希望外で \`+5\`、観戦/待機で \`+10\`）。
*   次回の配置ペナルティ計算時、\`現在のペナルティ - (Pity * 割引係数)\` として計算されるため、Pity値が高いプレイヤーほど優先的に希望レーンへ自動選出されるようになります。

---

## 3. チーム戦力平準化アルゴリズム

ロール配置確定後、チーム間の戦力を平準化するために以下の項目を2つのチームで評価し、差が最も小さくなるよう最終チーム分けを実行します。

1.  **対面MMR差の平準化**: 各レーン（例: Team A TOP vs Team B TOP）の対面同士のMMR差の2乗和を算出し、それが最小になるよう調整します。
2.  **総合MMR差の極小化**: チーム全体のMMR合計値の差を最小化します。
3.  **格上対面の保護**: MMR差が600以上開いている対面が発生する場合、追加の配置制限ペナルティを課して極端な一方通行マッチを回避します。
`
  },
  "match_record": {
    title: "📋 対戦結果登録とElo",
    filename: "02_match_record.md",
    content: `# 📋 対戦結果登録と MMR 計算ロジック

バランサーで決定されたチーム構成のもと、実際の対戦スコアや勝敗結果を手動登録し、その結果から全プレイヤーの各ロールのMMR（Eloレーティング）を更新する機能です。

---

## 1. 概要とデータ連携

*   **データソース（取得元）**: 
    *   結果登録フォーム（\`/balancer/record\`）に入力された勝敗、キル数等のスコア情報。
*   **データ追加・更新トリガー**:
    *   **完全な手動トリガー**: 管理者またはプレイヤーが対戦結果登録画面で「結果を送信」ボタンを手動で押した際に動作します（自動で登録されることはありません）。
    *   送信ボタン押下後、Supabase の \`ktm_matches\` テーブルに戦績履歴行が **自動追加 (INSERT)** され、関係した10名のプレイヤーの \`ktm_players.mmr\` および \`pity\` が **自動更新 (UPDATE)** されます。
*   **公開区分**: 一般ユーザー向け（誰でも結果登録が可能）

---

## 2. Elo レーティング計算アルゴリズム

試合終了後、プレイヤーのMMRの増減値（\\(\\Delta MMR\\)）は、以下の Elo 算式を適用して自動計算します。

### 2-1. MMR計算公式
\\[R_{new} = R_{old} + K \\cdot (S - E)\\]

*   \\(R_{old}\\): 試合前のロールMMR
*   \\(R_{new}\\): 試合後の新規MMR
*   \\(K\\): 変動重み係数。標準で \`32\` を適用。
*   \\(S\\): 実際の対戦結果の実績値。
    *   勝利したチームのメンバー: \`1\`
    *   敗北したチームのメンバー: \`0\`
*   \\(E\\): 期待勝率（レーン対面の強さに基づく勝率予測）。以下の数式で計算されます。
    \\[E = \\frac{1}{1 + 10^{(MMR_{opp} - MMR_{player}) / 400}}\\]
    *   \\(MMR_{opp}\\): レーン対面（同じロール）の敵プレイヤーの試合前MMR
    *   \\(MMR_{player}\\): 自身の試合前ロールMMR

### 2-2. 計算の特徴
*   自分より格上のプレイヤー（MMRが自分より遥かに高い相手）に勝利した場合、期待勝率 \\(E\\) が低いため、MMRの上昇量（\\(\\Delta MMR\\)）は非常に大きくなります。
*   逆に、自分より格下のプレイヤーに敗北した場合は、MMRの減少量が非常に大きくなります。
*   このロジックにより、対戦を重ねるにつれて全員のMMRが実力値に正確に収束していきます。
`
  },
  "leaderboard": {
    title: "🏆 プレイヤーリーダーボード",
    filename: "03_leaderboard.md",
    content: `# 🏆 プレイヤーリーダーボード & プレイ傾向計算

ポータルに参加している全プレイヤーの総合実力順位（リーダーボード）を表示し、個人の過去戦績から Aggressive (攻撃的), Farming (成長優先), Supportive (献身的) の3大プレイスタイルスライダーとプレイタグを算出・可視化する機能です。

---

## 1. 概要とデータ連携

*   **データソース（取得元）**:
    *   リーダーボード: Supabase \`ktm_players\` テーブルから各プレイヤーの最高MMRを取得してソート。
    *   プレイ傾向・スライダー・タグ: Supabase \`ktm_players.metadata.playstyle_cache\` にキャッシュされた JSON データを取得。
*   **データ追加・更新トリガー**:
    *   **KTMカスタムログ**: 対戦結果登録が手動で実行された際に、過去のKTMの全試合データからバックグラウンドで自動再計算・更新されます。
    *   **ソロキュー（SoloQ）ログ**: プレイヤー詳細画面（\`/player/[id]\`）の **「ソロQ戦績同期」ボタンをユーザーが手動で押したタイミング** で Riot API から最新10試合をフェッチし、プレイスタイルやタグが自動計算されて \`ktm_players.metadata.playstyle_cache.soloq\` に **自動キャッシュ保存 (UPDATE)** されます（API制限防止のため定期自動同期は行いません）。
*   **公開区分**: 一般ユーザー向け

---

## 2. プレイ傾向スライダー算出ロジック

過去のスタッツ（KDA、CS数、ダメージ量等）を標準化し、0%〜100% の範囲のスライダー値として算出します。

### 2-1. Aggressive (攻撃性 / アグレッシブ度)
*   **計算要素**: キル関与率（KP）、平均キル数、デス数（デスの少なさは反比例値）、1分あたりの与ダメージ（DPM）、ファーストブラッド（FB）関与率。
*   **処理仕様**: 各スタッツを平均値および標準偏差を用いて標準化し、戦闘的アクションが多いほど 100% に近づきます。

### 2-2. Farming (成長優先度 / ファーム度)
*   **計算要素**: CS/min（1分あたりCS獲得数）、チーム内ゴールド獲得シェア、ジャングルクリープ処理数。
*   **処理仕様**: 自身のリソース回収率を正規化して算出。ゴールドを独占してファームするほど 100% に近づきます。

### 2-3. Supportive (献身度 / サポート度)
*   **計算要素**: 視界スコア（Ward/min）、味方に与えたシールド/ヒール量、被ダメージシェア（タンク量）、アシスト率。
*   **処理仕様**: 味方をサポートする行動やタンクアクションが多いほど 100% に近づきます。

---

## 3. プレイスタイルタグ自動判定基準

スライダー値および特定のアクション発生率のしきい値判定により、プレイヤーの特徴タグを自動で付与します。

*   \`early-brawler\` (序盤の戦闘狂): Aggressive > 75% かつ 15分以内の戦闘キル関与率が平均より高い場合に自動付与。
*   \`speed-demon\` (快速ファーマー): Farming > 75% かつ 15分時点の平均CS獲得数が上位10%以内の場合に自動付与。
*   \`lane-bully\` (レーンの支配者): 対面スタッツ差分（ゴールド/CS差）の平均値が一定のしきい値を超えて有利な場合に自動付与。
`
  },
  "vs_analytics": {
    title: "⚔️ レーン対面分析 (VS)",
    filename: "04_vs_analytics.md",
    content: `# ⚔️ レーン対面分析 (VS Analytics) ＆ 9分スタッツ差分バー

バランサー確定時に対面ペア同士のプレイスタイルや9分時点でのレーン戦実力差（ゴールド/CS差）を可視化し、対面に勝つための具体的攻略アドバイス（Tips）を動的に出力する機能です。また、プレイヤー詳細では9分時点のスタッツ先行度（Diff Charts）を描画します。

---

## 1. 概要とデータ連携

*   **データソース（取得元）**:
    *   Supabase \`ktm_players.metadata.playstyle_cache\` 内のスタッツ（KTMカスタム、またはソロキュー情報）。
    *   Riot Match Timeline V5 API (ソロキュー同期実行時)。
*   **データ追加・更新トリガー**:
    *   「対戦結果登録」または「ソロQ戦績同期」が行われた際に、裏で自動的に9分スタッツ差分（ゴールド、XP、CS）が計算され、各プレイヤーのキャッシュデータに保存されます。
    *   バランサー画面（確定結果モーダル）を開いた際に、選択された10名のプレイヤーデータから対面ペアの比較情報が **その場で自動計算されて表示** されます（データベースへ追加で保存されるデータはありません）。
*   **公開区分**: 一般ユーザー向け

---

## 2. 9分時点の対面スタッツ差分（Diff Charts）の計算ロジック

ゲーム開始9分（レーン戦終了の目安）時点での対面とのゴールド差、XP差、CS差をグラフで可視化します。

### 2-1. Timeline データの取得 (Riot API 連携時)
*   Riot API の Match Timeline V5 からフレーム9（9分0秒時点）の各プレイヤーの \`currentGold\`、\`xp\`、\`minionsKilled\`、\`jungleMinionsKilled\` を取得し、対面相手の値との差分を直接計算します。

### 2-2. 過去ログ（タイムライン無し）での推定ロジック
*   タイムラインデータが存在しない過去ログ（またはRiot APIキー未設定の開発環境）では、プレイヤーの最終スタッツ（最終ゴールド、最終CS）と、そのチャンピオンの平均的な「周回・レーン戦減衰カーブ係数（チャンピオン固有値）」を用いて、9分時点のスタッツを数学的に推定・補間します。
*   **推定式**:
    \\[9分時点スタッツ = 最終スタッツ \\times チャンピオン固有減衰係数 \\times 補正係数\\]
    *   これにより、タイムラインAPIを毎回叩くことなく、9分時点の実力差分バーを安定して表示します。

---

## 3. VS Analytics 動的攻略アドバイス (Tips) 生成ロジック

対面ペアそれぞれの「プレイ傾向タグ」および「使用チャンピオン」に基づき、レーン戦の戦術アドバイスを JavaScript 側で動的に判定・生成（\`generateMatchupTip\`）します。

*   **戦闘狂タグ vs ファームタグ**: 「相手は序盤からキルを狙う戦闘狂タグを持っています。こちらはフルクリアと視界確保を優先し、相手が焦って仕掛けてくるのをタワー下で待ちましょう。」
*   **ファームタグ vs ファームタグ**: 「両者ともにファームを優先するスタイルです。中盤のオブジェクト争い（ドラゴンやヘラルド）での集団戦が勝負の鍵となります。デッドを避け、CS差での先行を目指しましょう。」
`
  },
  "jungle_clears": {
    title: "🌳 周回統計ライブラリ",
    filename: "05_jungle_clears.md",
    content: `# 🌳 ジャングル周回統計ライブラリ ＆ 動画プレイヤー

各ジャングルチャンピオンの最速クリアタイム目標、周回ルート、カイトのコツ、および実演動画をインライン再生する攻略ライブラリ機能です。

---

## 1. 概要とデータ連携

*   **データソース（取得元）**:
    *   **完全なフロントエンド静的データ (Static Master Data)**: データベース（Supabase等）は参照しておらず、すべてのデータ（チャンピオン名、開始サイド、ルート、最速タイム、YouTube動画ID、Tips）はフロントエンドのソースコード内に定数として定義されています。
*   **データ追加・更新トリガー**:
    *   **完全な手動によるコード編集**: データベースを介さないため、新しいチャンピオンや動画のURLを追加・修正する場合は、**\`src/app/admin/clears/page.tsx\` のコードを直接書き換える** 必要があります（自動で追加・更新されることはありません）。
*   **公開区分**: **管理者専用 🔑** (サイドバーおよびルーティングを \`/admin/clears\` パスに制限し、管理者のみがアクセス・確認できるように保護しています)。

---

## 2. インライン動画プレイヤーの仕組み

画面遷移や外部アプリ（YouTube等）の起動を挟まずに、ポータル内で直接動画を再生するためのインラインポップアッププレイヤーを備えています。

*   **再生方式 (YouTube Embed)**:
    *   静的マスターデータ内に登録された YouTube の \`videoUrl\` (11桁のビデオID、例: \`tq6wQ40f7d4\`) を利用し、ポップアップモーダルの中に \`<iframe>\` を埋め込んで自動再生します。
    *   **埋め込み形式**:
        \`\`\`html
        <iframe src="https://www.youtube.com/embed/[videoUrl]?autoplay=1" ...></iframe>
        \`\`\`
*   **フィルタリング**:
    *   チャンピオン名によるテキスト検索、クリア難易度（EASY / MEDIUM / HARD）、および開始バフサイド（BLUE / RED）のタグ情報を React State でハンドリングし、配列の \`filter()\` 処理で瞬時に情報を絞り込みます。
`
  },
  "soloq_scout": {
    title: "🔍 ソロQ対面リアルタイム偵察",
    filename: "06_soloq_scout.md",
    content: `# 🔍 ソロQ対面リアルタイム偵察 (Live Match Lookup)

管理者が自身の Riot ID（または他のプレイヤーのID）を入力して実行し、現在進行中のライブゲームを検知して、敵のジャングラーのプレイスタイル、開始バフ予測、初動Gank（レーン関与）予測、および具体的な対策Tipsを出力する機能です。

---

## 1. 概要とデータ連携

*   **データソース（取得元）**:
    *   **Riot Games 公式 API**:
        *   Riot ID 解決: \`/riot/account/v1/accounts/by-riot-id/\`
        *   進行中ゲーム (Spectator-V5): \`/lol/spectator/v5/active-games/by-puuid/\`
        *   敵ジャングラーの過去戦績: \`/lol/match/v5/matches/by-puuid/\` および \`/timeline\`
*   **データ追加・更新トリガー**:
    *   **手動リアルタイムフェッチ（使い捨てデータ）**:
        *   管理者がサモナー名（Riot ID）を入力し、「偵察開始」ボタンを **手動で押したタイミングでのみ** リアルタイムに Riot API からデータを引き出し、その場でメモリ上だけで計算・表示します。
        *   データベース（Supabase）には分析結果や検索履歴などは一切保存されず、完全に「その場限り」の使い捨てデータです（自動巡回や定期自動保存はされません）。
        *   ※ \`RIOT_API_KEY\`（環境変数）が未設定の開発・デモ環境では、Lee Sin を対面とするダミーの模擬ライブデータを自動生成して返却する「モックフォールバック機能」が自動で起動します。
*   **公開区分**: **管理者専用 🔑** (パス: \`/admin/soloq\`)

---

## 2. 敵ジャングラー特定 ＆ 戦術予測アルゴリズム

### 2-1. 敵ジャングラーの特定
1.  API（\`/lol/spectator/v5/active-games/by-puuid/\`）から、進行中のゲームの全参加者（10名）のサモナースペルおよびチームIDを取得します。
2.  検索されたサモナーのチームIDを特定し、敵チーム（もう一方のチームID）にいるプレイヤーの中から、召喚士スペルに **Smite（ID: 11）を装備しているプレイヤー** を「敵ジャングラー」として自動特定します。

### 2-2. 開始バフ（赤/青）＆ 初動Gank（レーン関与）の予測
敵の「使用チャンピオン」と「過去のプレイスタイルタグ」から、AI/ロジックで初動ルートを推測します。

*   **戦闘狂タイプ (例: Lee Sin, Nidalee, Shaco 等の早期Gankチャンピオン)**:
    *   **予測バフ**: 「青バフ（バフ3キャンプ速攻）スタート予測」または「ボット側リーシュあり赤バフスタート」。
    *   **予測Gank**: 「トップまたはミッドへのLV3早期Gank」「リバーでの遭遇戦」。
*   **ファーム・成長優先タイプ (例: Graves, Karthus 等のフルクリアチャンピオン)**:
    *   **予測バフ**: 「赤バフ（フルクリア周回）スタート予測」。
    *   **予測Gank**: 「フルクリア後のLV4でのスカトル争い、または最初のオブジェクト関与」。
*   **対策アドバイスの生成**:
    敵のプレイスタイルタグ（例: \`early-brawler\` [戦闘狂] や \`speed-demon\` [ファーマー]）に基づき、開始3分前後にどのレーンにワードを置くべきかなどの具体的な戦術テキストを動的に生成します。
`
  },
  "mmr_admin": {
    title: "⚙️ MMR一括再計算・検証",
    filename: "07_mmr_admin.md",
    content: `# ⚙️ MMR一括再計算 ＆ 整合性検証

過去の対戦戦績データから、プレイヤーの全レーンMMRおよび総合MMRを時系列に沿って一括で再構築し、データの整合性を厳密に検証する管理者専用機能です。

---

## 1. 概要とデータ連携

*   **データソース（取得元）**:
    *   Supabase \`ktm_matches\` テーブル（過去の全戦績データ）。
    *   Supabase \`ktm_players\` テーブル（全プレイヤーの現在のMMR）。
*   **データ追加・更新トリガー**:
    *   **完全な手動トリガー**: 管理者が管理者専用ダッシュボード（\`/ktm-admin\`）から「MMR一括再計算」または「整合性検証」ボタンを **手動でクリックした時のみ** 実行されます（自動で再計算されることはありません）。
    *   再計算実行時、既存の \`ktm_players\` の全 MMR レコードが **自動で上書き更新 (UPDATE)** されます。
*   **公開区分**: **管理者専用 🔑**

---

## 2. MMR 一括再計算（Rebuild）の処理仕様

対戦結果の削除やMMR計算式の変更時に、整合性を保つために以下のプロセスで全プレイヤーのMMRを再計算します。

1.  **初期化**: 全プレイヤーのMMRを、それぞれの「自己申告の最高ランクおよび希望ロール」に基づく初期値に一度一括リセットします。
2.  **時系列ループ処理**:
    *   \`ktm_matches\` から全試合データを「日付・作成日時が古い順（昇順）」で一括取得します。
    *   第1試合から順番に、その試合に参加した10名のその時点でのMMRを取り出し、Elo計算式を適用して勝敗による増減値（\\(\\Delta MMR\\)）を算出します。
    *   算出された新MMRをそのプレイヤーの「現在MMR」に適用し、次の試合へと進みます。
3.  **バッチ保存**: 全試合のシミュレーションループ完了後、全プレイヤーの最終MMRおよび各試合の \\(\\Delta MMR\\) 変動履歴を Supabase に一括保存（UPDATE）します。

---

## 3. MMR 整合性検証（Check Integrity）の処理仕様

メモリ上で計算した累積MMRシミュレーション値と、データベースに実際に保存されている最終MMR値にズレがないかを自動検証します。

*   **ロール名の表記揺れ吸収**: 参加者データからロールキー名を生成する際、ロール名を \`toUpperCase()\` に変換して \`expectedJg\` / \`expectedSup\` などのキャメルケースで正しく期待値を読み込みます。
*   **浮動小数点丸め誤差の保護（しきい値）**:
    *   データベース保存時の丸め処理や、プログラム内の浮動小数点演算（IEEE 754）に伴う微小なズレ（1〜2点程度）をエラーと判定する偽陽性を防ぐため、各レーンの差が **\`2\` 以内** であれば正常（整合性あり）と判定するセーフガード設計となっています。
`
  },
  "knowledge_base": {
    title: "🧠 自動要約ナレッジ＆動画キュー",
    filename: "08_knowledge_base.md",
    content: `# 🧠 自動要約ナレッジベース ＆ YouTube自動解析キュー

ITツールのアフィリエイトノウハウやLoL攻略情報などのテキストドキュメントを管理し、YouTubeの攻略動画からAI（Gemini）によって攻略バイブルを自動生成・マージする管理者専用ナレッジシステムです。

---

## 1. 概要とデータ連携

*   **データソース（取得元）**:
    *   Supabase \`personal_knowledge\` テーブル（攻略記事や要約された戦術メモの保存先）。
    *   Supabase \`matchup_sentinel\` テーブル（チャンピオン辞典）。
    *   ローカルファイル \`04_PORTAL/kirei_queue.json\` (動画解析のタスクキュー)。
*   **データ追加・更新トリガー（自動 ＆ 手動の協調）**:
    *   **手動登録**: 管理者がURLやメモをフォーム（\`/admin/knowledge\`）に入力し、「追加」ボタンを手動で押した際に登録されます。
    *   **YouTube自動要約（完全自動追加）**: 
        *   登録されたURLが YouTube 動画の場合、SREデーモン（Python）が15分おきに自動巡回し、動画字幕をフェッチ。Gemini API で要約された Markdown 形式の攻略バイブルを **自動生成してナレッジDBへ追加 (INSERT)** します。
        *   その後、3時間ごとに \`DictSynthesizer\` が自動起動し、生成された攻略Markdownを対面アドバイス用DB \`matchup_sentinel\` へ自動マージ・同期します。
*   **公開区分**: **管理者専用 🔑** (パス: \`/admin/knowledge\`, \`/admin/youtube\`)

---

## 2. YouTube動画解析 ＆ 攻略バイブル生成のフロー

攻略動画の登録から最終マージまでの全自律フローは以下の通りです。

1.  **キュー登録**: 管理者が YouTube URL を登録すると、ステータス \`pending\` で \`kirei_queue.json\` に追加されます。
2.  **字幕解析**: SREデーモン（15分間隔）が起動し、\`yt-dlp\` を用いて英語/日本語の字幕（VTT）をダウンロードします。
3.  **AI要約**: 字幕テキストを Gemini API (\`gemini-2.5-pro\` / Paid) に渡し、LoLの戦術・周回ルート・マッチアップを日本語で要約した Markdown 文書（バイブル）を生成させます。
4.  **DB追加**: 生成された Markdown データを \`personal_knowledge\` に自動追加し、キューのステータスを \`completed\` に更新します。

---

## 3. チャンピオン辞典への自動同期マージ

3時間おきに起動する \`DictSynthesizer\` が、以下のロジックでナレッジ記事をチャンピオン辞典（対面分析のTips）へマージします。

*   ナレッジ記事内の対象チャンピオン（例: \`Nidalee\`）を検知。
*   対戦アドバイス用DB（\`matchup_sentinel\`）の該当チャンピオンの戦略レコードをロード。
*   既存の戦略テキストの末尾に、重複しないように今回の攻略 Markdown 差分を自動的にマージ（追記）して保存します。
*   マージ完了した元記事には \`__DELETED__\` タグが付与され、SREデーモンによって15秒後にDBおよびローカルファイルから安全に物理削除されます。
`
  },
  "affiliate_spa": {
    title: "💵 アフィリエイト収益化SPA",
    filename: "09_affiliate_spa.md",
    content: `# 💵 アフィリエイト収益化SPAコントロール

IT自動アフィリエイト運用のアクセス分析、案件リンクの編集、自動記事生成バッチ（ドライラン/本番）の監視コンソールなどを一元管理する管理者用のSPA（Single Page Application）機能です。

---

## 1. 概要とデータ連携

*   **データソース（取得元）**:
    *   Supabase \`note_pv_history\` テーブル（PV、Likes、Comments数などのnoteアクセス履歴）。
    *   ローカルファイル \`02_FACTORY/affiliate_links.json\` (アフィリエイトリンクの一覧)。
    *   ローカルファイル \`02_FACTORY/affiliate_knowledge.md\` (副業運用メモ)。
    *   ローカルログ \`00_LOGS/monetization_batch_run.log\` (バッチ実行ログ)。
*   **データ追加・更新トリガー**:
    *   **アクセス分析 (自動取得)**: アナリストバッチが定期的に note.com からデータをスクレイピング（またはAPI連携）して \`note_pv_history\` を更新し、Gemini が週次でアクセス傾向へのAIフィードバックを生成します。
    *   **案件リンク管理 (手動保存)**: 管理者がツール名とアフィリエイトURLをフォームに入力し、「リンクの保存」ボタンを **手動で押した時のみ** \`affiliate_links.json\` に上書き保存 (UPDATE) されます。
    *   **自動記事生成バッチ (手動キック ＆ 自動実行)**: 
        *   「バッチを実行」ボタンを **手動でクリック** することで、Python子プロセスが非同期で起動してバッチ処理が始まります。
        *   実行ログ（コンソール出力）は自動的に \`monetization_batch_run.log\` に書き込まれ、ポータル画面上の黒い疑似コンソールに **自動でリアルタイムストリーム表示** されます。
*   **公開区分**: **管理者専用 🔑** (パス: \`/admin/dashboard\` タブ)

---

## 2. アフィリエイト一気通貫バッチの自動処理フロー

バッチを実行すると、以下のライフサイクルが自律的に回ります。

1.  **ITトレンド収集**: リサーチャー（Python）がホットなAI・副業トレンド情報をインターネットから収集します。
2.  **記事の自動生成**: クリエイター（Python）が、収集したトレンドと \`affiliate_links.json\` に登録されている紹介用アフィリエイトURLをブレンドし、アフィリエイトリンク入りの note 有料記事案（Markdown）を自動で執筆・生成します。
3.  **note 下書き自動保存 ＆ Xスレッド自動投稿**:
    *   Playwright ヘッドレスブラウザが起動し、自動で note.com にログインして下書き保存を実行。同時に、X (Twitter) の宣伝用ツイートスレッドを自動投稿します。
    *   ※ 「ドライラン（検証実行）」チェックを有効にして実行した場合、記事の生成やXスレッドの構築までは行いますが、note への実際の保存や X への投稿は行わずに挙動をテストできます。
`
  },
};
