-- KTM Phase 2: 戦績・統計用のテーブル設計

-- 1. 試合自体の履歴テーブル
CREATE TABLE IF NOT EXISTS public.ktm_matches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  winning_team varchar(10) NOT NULL, -- 'BLUE' or 'RED'
  game_duration integer,             -- 試合時間（秒）
  riot_match_id varchar(50)          -- Riot API の Match ID (あれば)
);

-- 2. 各試合の参加者ごとの詳細成績テーブル
CREATE TABLE IF NOT EXISTS public.ktm_match_participants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id bigint REFERENCES public.ktm_matches(id) ON DELETE CASCADE,
  player_name varchar(50) NOT NULL,  -- ktm_players の name と紐づく想定
  team varchar(10) NOT NULL,         -- 'BLUE' or 'RED'
  role varchar(10) NOT NULL,         -- 'TOP', 'JG', 'MID', 'ADC', 'SUP'
  
  -- Riot API連携後のスタッツ用
  kills integer DEFAULT 0,
  deaths integer DEFAULT 0,
  assists integer DEFAULT 0,
  vision_score integer DEFAULT 0,
  kda_score numeric(4,2),            -- パフォーマンススコア(1.0〜8.0)
  
  -- MMRの変動量（プラスマイナス）
  mmr_delta integer NOT NULL DEFAULT 0,
  
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 検索最適化のためのインデックス
CREATE INDEX IF NOT EXISTS idx_ktm_match_participants_match_id ON public.ktm_match_participants(match_id);
CREATE INDEX IF NOT EXISTS idx_ktm_match_participants_player_name ON public.ktm_match_participants(player_name);
CREATE INDEX IF NOT EXISTS idx_ktm_match_participants_role ON public.ktm_match_participants(role);

-- RLS（Row Level Security）の有効化（全員読み取り可能）
ALTER TABLE public.ktm_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ktm_match_participants ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.ktm_matches FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON public.ktm_match_participants FOR SELECT USING (true);

-- API経由での追加を許可するポリシー (KTMボットからのPOST想定)
CREATE POLICY "Enable insert access for all users" ON public.ktm_matches FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert access for all users" ON public.ktm_match_participants FOR INSERT WITH CHECK (true);
