const fs = require('fs');
const path = require('path');

const srcPath = path.join(__dirname, '../SYSTEM_DESIGN.md');
const destDir = path.join(__dirname, 'src/app/design');
const destPath = path.join(destDir, 'SYSTEM_DESIGN.md');
const tsPath = path.join(destDir, 'systemDesignMarkdown.ts');

try {
  if (fs.existsSync(srcPath)) {
    // ディレクトリが存在しない場合は作成
    if (!fs.existsSync(destDir)) {
      fs.mkdirSync(destDir, { recursive: true });
    }
    // Markdownファイルをコピー
    fs.copyFileSync(srcPath, destPath);
    console.log('✅ [Sync] SYSTEM_DESIGN.md has been copied to portal src.');

    // TypeScriptファイルとしてエクスポートする文字列を生成
    const markdownContent = fs.readFileSync(srcPath, 'utf8');
    // バッククォートやバックスラッシュ、ドル記号などをエスケープ
    const escapedContent = markdownContent
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\${/g, '\\${');
    
    const tsContent = `// This file is auto-generated by copy_design.js. Do not edit directly.\nexport const systemDesignMarkdown = \`${escapedContent}\`;\n`;
    fs.writeFileSync(tsPath, tsContent, 'utf8');
    console.log('✅ [Sync] systemDesignMarkdown.ts has been generated.');
  } else {
    console.log('⚠️ [Sync] Source SYSTEM_DESIGN.md not found. Skipping copy to keep existing file.');
  }
} catch (err) {
  console.error('❌ [Sync] Failed to copy SYSTEM_DESIGN.md:', err.message);
}
