const fs = require('fs');
const path = require('path');

const docsSrcDir = path.join(__dirname, '../design_docs');
const destDir = path.join(__dirname, 'src/app/design');
const tsPath = path.join(destDir, 'systemDesignMarkdown.ts');

const titleMapping = {
  '00_overview': '🌟 全体概要・アーキテクチャ',
  '01_balancer': '⚖️ MMRバランサー・チーム分け',
  '02_match_record': '📋 対戦結果登録とElo',
  '03_leaderboard': '🏆 プレイヤーリーダーボード',
  '04_vs_analytics': '⚔️ レーン対面分析 (VS)',
  '05_jungle_clears': '🌳 周回統計ライブラリ',
  '06_soloq_scout': '🔍 ソロQ対面リアルタイム偵察',
  '07_mmr_admin': '⚙️ MMR一括再計算・検証',
  '08_knowledge_base': '🧠 自動要約ナレッジ＆動画キュー',
  '09_affiliate_spa': '💵 アフィリエイト収益化SPA'
};

try {
  if (fs.existsSync(docsSrcDir)) {
    if (!fs.existsSync(destDir)) {
      fs.mkdirSync(destDir, { recursive: true });
    }

    const files = fs.readdirSync(docsSrcDir).filter(f => f.endsWith('.md')).sort();
    let tsContent = `// This file is auto-generated by copy_design.js. Do not edit directly.\n\n`;
    tsContent += `export interface DesignDoc {\n  title: string;\n  content: string;\n  filename: string;\n}\n\n`;
    tsContent += `export const systemDesignDocs: Record<string, DesignDoc> = {\n`;

    files.forEach(file => {
      const filePath = path.join(docsSrcDir, file);
      const rawKey = path.basename(file, '.md');
      const cleanKey = rawKey.replace(/^\d+_/g, '');
      const markdownContent = fs.readFileSync(filePath, 'utf8');

      // JSON.stringify を使って改行やバッククォート、バックスラッシュを完璧に安全にエスケープ
      const safeJsonContentString = JSON.stringify(markdownContent);

      const title = titleMapping[rawKey] || cleanKey;
      tsContent += `  "${cleanKey}": {\n`;
      tsContent += `    title: "${title}",\n`;
      tsContent += `    filename: "${file}",\n`;
      tsContent += `    content: ${safeJsonContentString}\n`;
      tsContent += `  },\n`;
      
      // ポータル側 src フォルダへも Markdown 本体をそのままコピー保存 (バックアップ・ローカル編集同期用)
      const portalCopyPath = path.join(destDir, file);
      fs.writeFileSync(portalCopyPath, markdownContent, 'utf8');
    });

    tsContent += `};\n`;
    fs.writeFileSync(tsPath, tsContent, 'utf8');
    console.log('✅ [Sync] systemDesignMarkdown.ts and individual markdown copies have been successfully generated.');
  } else {
    console.log('⚠️ [Sync] design_docs directory not found. Skipping synchronization.');
  }
} catch (err) {
  console.error('❌ [Sync] Failed to synchronize design documents:', err.message);
}
