/**
 * チャンピオン名の表記揺れ正規化（DataDragon準拠のIDに寄せる）。
 * 元々 src/app/api/coach/analyze/route.ts にだけローカル定義されていたため、
 * champion_power_spikes 等の新しいテーブルを検索する別の場所を書くたびに
 * 同じマップを再実装するリスクがあった。共通化してここに一本化する。
 */
export const CHAMPION_NAME_MAP: Record<string, string> = {
  // 英語表記ゆれ
  'khazix': 'Khazix',
  'kha\'zix': 'Khazix',
  'kha zix': 'Khazix',
  'leesin': 'LeeSin',
  'lee sin': 'LeeSin',
  'xin zhao': 'XinZhao',
  'xinzhao': 'XinZhao',
  'jarvan': 'JarvanIV',
  'jarvan iv': 'JarvanIV',
  'jarvaniv': 'JarvanIV',
  'drmundo': 'DrMundo',
  'dr. mundo': 'DrMundo',
  'dr mundo': 'DrMundo',
  'nunu': 'Nunu',
  'nunu & willump': 'Nunu',
  'nunu and willump': 'Nunu',
  'wukong': 'MonkeyKing',
  'monkey king': 'MonkeyKing',
  'tahm kench': 'TahmKench',
  'tahmkench': 'TahmKench',
  'twisted fate': 'TwistedFate',
  'twistedfate': 'TwistedFate',
  'tf': 'TwistedFate',

  // ここから下はPython側(champ_id_normalizer.py の KNOWN_ALIASES)にあってこちらに
  // 無かった別名。表記ゆれ正規化のロジックがPython/TypeScriptで別実装のまま放置されると
  // 片方だけ別名を追加した際に重複レコードが再発する(2026-08-05の実例と同型、
  // 2026-08-13の辞典更新パイプライン監査#5で発覚)。完全な一本化(共有ソース化)は
  // 別途の大きめの作業になるため、まず既知の差分をここに追いつかせる。
  'renata glasc': 'Renata',
  'renata': 'Renata',
  'kisante': 'KSante',
  'ksante': 'KSante',
  "k'sante": 'KSante',
  'kfsante': 'KSante',
  'qiyana': 'Qiyana',
  'nilah': 'Nilah',
  'silas': 'Sylas',
  'sylas': 'Sylas',
  'zilian': 'Zilean',
  'zilean': 'Zilean',
  'viper': 'Viego',
  'viego': 'Viego',
  'evelyn': 'Evelynn',
  'evelynn': 'Evelynn',
  'victor': 'Viktor',
  'viktor': 'Viktor',
  'pike': 'Pyke',
  'pyke': 'Pyke',
  'yi': 'MasterYi',
  'master yi': 'MasterYi',
  'masteryi': 'MasterYi',
  'lilia': 'Lillia',
  'lillia': 'Lillia',
  'miss fortune': 'MissFortune',
  'missfortune': 'MissFortune',
  'aurelion sol': 'AurelionSol',
  'aurelionsol': 'AurelionSol',
  "kai'sa": 'Kaisa',
  'kaisa': 'Kaisa',
  "vel'koz": 'Velkoz',
  'velkoz': 'Velkoz',
  "cho'gath": 'Chogath',
  'chogath': 'Chogath',
  "kog'maw": 'KogMaw',
  'kogmaw': 'KogMaw',
  "rek'sai": 'RekSai',
  'reksai': 'RekSai',
  "bel'veth": 'Belveth',
  'belveth': 'Belveth',
  'hecrim': 'Hecarim',
  'hecarim': 'Hecarim',
  'kane': 'Kayn',
  'kayn': 'Kayn',
  'nasis': 'Nasus',
  'nassos': 'Nasus',
  'nasus': 'Nasus',
  'mumu': 'Amumu',
  'jace': 'Jayce',
  'naufrieli': 'Naafiri',
  'naafiri': 'Naafiri',
  'ailious': 'Aphelios',

  // カタカナ・ひらがな日本語名
  'アーリ': 'Ahri', 'あーり': 'Ahri',
  'エイトロックス': 'Aatrox', 'えいとろっくす': 'Aatrox',
  'リーシン': 'LeeSin', 'リー・シン': 'LeeSin', 'りーしん': 'LeeSin',
  'ヤスオ': 'Yasuo', 'やすお': 'Yasuo',
  'ヨネ': 'Yone', 'よね': 'Yone',
  'グレイブス': 'Graves', 'ぐれいぶす': 'Graves',
  'ヴィエゴ': 'Viego', 'びえご': 'Viego',
  'ゼド': 'Zed', 'ぜど': 'Zed',
  'ダリウス': 'Darius', 'だりうす': 'Darius',
  'ガレン': 'Garen', 'がれん': 'Garen',
  'ラックス': 'Lux', 'らっくす': 'Lux',
  'カイサ': 'Kaisa', 'かいさ': 'Kaisa',
  'ジンクス': 'Jinx', 'じんくす': 'Jinx',
  'ノーチラス': 'Nautilus', 'のーちらす': 'Nautilus',
  'スレッシュ': 'Thresh', 'すれっしゅ': 'Thresh',
  'ルル': 'Lulu', 'るる': 'Lulu',
  'レオナ': 'Leona', 'れおな': 'Leona',
  'カタリナ': 'Katarina', 'かたりな': 'Katarina',
  'アカリ': 'Akali', 'あかり': 'Akali',
  'サイラス': 'Sylas', 'さいらす': 'Sylas',
  'オリアナ': 'Orianna', 'おりあな': 'Orianna',
  'シンドラ': 'Syndra', 'しんどら': 'Syndra',
  'ビクター': 'Viktor', 'びくたー': 'Viktor',
  'エズリアル': 'Ezreal', 'えずりある': 'Ezreal',
  'ヴェイン': 'Vayne', 'ゔぇいん': 'Vayne',
  'ルシアン': 'Lucian', 'るしあん': 'Lucian',
  'ケイン': 'Kayn', 'けいん': 'Kayn',
  'キンドレッド': 'Kindred', 'きんどれっど': 'Kindred',
  'シャコ': 'Shaco', 'しゃこ': 'Shaco',
  'マスターイー': 'MasterYi', 'マスター・イー': 'MasterYi', 'ますたーいー': 'MasterYi',
  'ニダリー': 'Nidalee', 'にだりー': 'Nidalee',
  'エリス': 'Elise', 'えりす': 'Elise',
  'レク＝サイ': 'RekSai', 'レックサイ': 'RekSai', 'れっくさい': 'RekSai',
  'フィドルスティックス': 'Fiddlesticks', 'ふぃどる': 'Fiddlesticks',
  'ヘカリム': 'Hecarim', 'へかりむ': 'Hecarim',
  'カーサス': 'Karthus', 'かーさす': 'Karthus',
  'リリア': 'Lillia', 'りりあ': 'Lillia',
  'ブライアー': 'Briar', 'ぶらいあー': 'Briar',
  'ベルヴェス': 'Belveth', 'べるゔぇす': 'Belveth',

  // ここから下はDataDragon(ja_JP)の公式ローカライズ名から自動生成（2026-08-04）。
  // 上記の手動登録分(約47体)以外の全チャンピオンを網羅する。
  // 生成元: ddragon.leagueoflegends.com/cdn/{patch}/data/ja_JP/champion.json
  // ※ "Jade_XXX"のような派生フォームIDは除外し、本体チャンピオンにのみ対応付けている。
  'アクシャン': 'Akshan',
  'アリスター': 'Alistar',
  'アンベッサ': 'Ambessa',
  'アムム': 'Amumu',
  'アニビア': 'Anivia',
  'アニー': 'Annie',
  'アフェリオス': 'Aphelios',
  'アッシュ': 'Ashe',
  'オレリオン・ソル': 'AurelionSol', 'オレリオンソル': 'AurelionSol',
  'オーロラ': 'Aurora',
  'アジール': 'Azir',
  'バード': 'Bard',
  'ブリッツクランク': 'Blitzcrank',
  'ブランド': 'Brand',
  'ブラウム': 'Braum',
  'ケイトリン': 'Caitlyn',
  'カミール': 'Camille',
  'カシオペア': 'Cassiopeia',
  'チョ＝ガス': 'Chogath', 'チョガス': 'Chogath',
  'コーキ': 'Corki',
  'ダイアナ': 'Diana',
  'ドレイヴン': 'Draven',
  'エコー': 'Ekko',
  'イブリン': 'Evelynn',
  'フィオラ': 'Fiora',
  'フィズ': 'Fizz',
  'ガリオ': 'Galio',
  'ガングプランク': 'Gangplank',
  'ナー': 'Gnar',
  'グラガス': 'Gragas',
  'グウェン': 'Gwen',
  'ハイマーディンガー': 'Heimerdinger',
  'フェイ': 'Hwei',
  'イラオイ': 'Illaoi',
  'イレリア': 'Irelia',
  'アイバーン': 'Ivern',
  'ジャンナ': 'Janna',
  'ジャックス': 'Jax',
  'ジェイス': 'Jayce',
  'ジン': 'Jhin',
  'カリスタ': 'Kalista',
  'カルマ': 'Karma',
  'カサディン': 'Kassadin',
  'ケイル': 'Kayle',
  'ケネン': 'Kennen',
  'カ＝ジックス': 'Khazix', 'カジックス': 'Khazix',
  'クレッド': 'Kled',
  'コグ＝マウ': 'KogMaw', 'コグマウ': 'KogMaw',
  'カ・サンテ': 'KSante', 'カサンテ': 'KSante',
  'ルブラン': 'Leblanc',
  'リサンドラ': 'Lissandra',
  'ロック': 'Locke',
  'マルファイト': 'Malphite',
  'マルザハール': 'Malzahar',
  'マオカイ': 'Maokai',
  'メル': 'Mel',
  'ミリオ': 'Milio',
  'ミス・フォーチュン': 'MissFortune', 'ミスフォーチュン': 'MissFortune',
  'モルデカイザー': 'Mordekaiser',
  'モルガナ': 'Morgana',
  'ナフィーリ': 'Naafiri',
  'ナミ': 'Nami',
  'ナサス': 'Nasus',
  'ニーコ': 'Neeko',
  'ニーラ': 'Nilah',
  'ノクターン': 'Nocturne',
  'オラフ': 'Olaf',
  'オーン': 'Ornn',
  'パンテオン': 'Pantheon',
  'ポッピー': 'Poppy',
  'パイク': 'Pyke',
  'キヤナ': 'Qiyana',
  'クイン': 'Quinn',
  'ラカン': 'Rakan',
  'ラムス': 'Rammus',
  'レル': 'Rell',
  'レナータ・グラスク': 'Renata', 'レナータグラスク': 'Renata',
  'レネクトン': 'Renekton',
  'レンガー': 'Rengar',
  'リヴェン': 'Riven',
  'ランブル': 'Rumble',
  'ライズ': 'Ryze',
  'サミーラ': 'Samira',
  'セジュアニ': 'Sejuani',
  'セナ': 'Senna',
  'セラフィーン': 'Seraphine',
  'セト': 'Sett',
  'シェン': 'Shen',
  'シヴァーナ': 'Shyvana',
  'シンジド': 'Singed',
  'サイオン': 'Sion',
  'シヴィア': 'Sivir',
  'スカーナー': 'Skarner',
  'スモルダー': 'Smolder',
  'ソナ': 'Sona',
  'ソラカ': 'Soraka',
  'スウェイン': 'Swain',
  'タリヤ': 'Taliyah',
  'タロン': 'Talon',
  'タリック': 'Taric',
  'ティーモ': 'Teemo',
  'トリスターナ': 'Tristana',
  'トランドル': 'Trundle',
  'トリンダメア': 'Tryndamere',
  'トゥイッチ': 'Twitch',
  'ウディア': 'Udyr',
  'アーゴット': 'Urgot',
  'ヴァルス': 'Varus',
  'ベイガー': 'Veigar',
  'ヴェル＝コズ': 'Velkoz', 'ヴェルコズ': 'Velkoz',
  'ヴェックス': 'Vex',
  'ヴァイ': 'Vi',
  'ブラッドミア': 'Vladimir',
  'ボリベア': 'Volibear',
  'ワーウィック': 'Warwick',
  'ザヤ': 'Xayah',
  'ゼラス': 'Xerath',
  'ヨリック': 'Yorick',
  'ユナラ': 'Yunara',
  'ユーミ': 'Yuumi',
  'ザーヘン': 'Zaahen',
  'ザック': 'Zac',
  'ゼリ': 'Zeri',
  'ジグス': 'Ziggs',
  'ジリアン': 'Zilean',
  'ゾーイ': 'Zoe',
  'ザイラ': 'Zyra',
};

export function normalizeChampionName(name: string): string {
  if (!name) return '';
  const key = name.toLowerCase().trim();
  if (CHAMPION_NAME_MAP[key]) return CHAMPION_NAME_MAP[key];

  // 先頭を大文字、それ以降を小文字に（例: graves -> Graves）
  return name.charAt(0).toUpperCase() + name.slice(1).toLowerCase();
}

/** 検索タグやDB比較用に表記揺れリストを展開する */
export function getChampionSearchVariations(name: string): string[] {
  const normalized = normalizeChampionName(name);
  const variations = [normalized];

  if (normalized === 'Khazix') variations.push("Kha'Zix", "Kha Zix");
  if (normalized === 'LeeSin') variations.push("Lee Sin");
  if (normalized === 'XinZhao') variations.push("Xin Zhao");
  if (normalized === 'JarvanIV') variations.push("Jarvan IV", "Jarvan");
  if (normalized === 'DrMundo') variations.push("Dr. Mundo", "Dr Mundo", "Mundo");
  if (normalized === 'MonkeyKing') variations.push("Wukong", "Monkey King");
  if (normalized === 'TahmKench') variations.push("Tahm Kench");
  if (normalized === 'TwistedFate') variations.push("Twisted Fate", "TF");
  if (normalized === 'Nunu') variations.push("Nunu & Willump", "Nunu and Willump");

  return variations;
}
